# Generated by Django 4.2.8 on 2023-12-14 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_billingdetails_order_billing_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.billingdetails'),
        ),
    ]
