# Generated by Django 4.2.8 on 2023-12-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_order_billing_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetails',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
