# Generated by Django 4.2.8 on 2023-12-15 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_billingdetails_company_name_billingdetails_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingdetails',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='billingdetails',
            name='country',
        ),
        migrations.RemoveField(
            model_name='billingdetails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='billingdetails',
            name='order_notes',
        ),
        migrations.RemoveField(
            model_name='billingdetails',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='billingdetails',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='billingdetails',
            name='town_city',
        ),
        migrations.RemoveField(
            model_name='billingdetails',
            name='zip_code',
        ),
    ]
