# Generated by Django 4.2.8 on 2023-12-17 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_wishlist_product_wishlist_products_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
