# Generated by Django 4.2.8 on 2023-12-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_cart_products_cartproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(to='myapp.product'),
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
    ]
