# Generated by Django 4.2.8 on 2023-12-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_cart_products_delete_cartproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetails',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
